alertmanager:
  enabled: false
  ingress:
    enabled: false
grafana:
  enabled: false
prometheus:
  enabled: true
  ingress:
    enabled: false
  prometheusSpec:
    enableRemoteWriteReceiver: true
    externalLabels:
      cluster: ec2-application-obs-demo
    remoteWrite:
    - name: prometheus-otlp-central
      sendExemplars: true
      url: http://52.22.17.171:30002/api/v1/write
    scrapeInterval: 10s
prometheus-node-exporter:
  hostRootFsMount:
    enabled: false
prometheusOperator:
  enabled: true
