apiVersion: veecode.backstage.io/v1alpha1
kind: Cluster
metadata:
  name: "ec2-application-obs-demo"
  environment:
    cluster_type: ec2
    domain: pet.platform.vee.codes
    ingress_type: kong
    certificate_account_email: platformss@vee.codes
    certificate_environment_type: staging
    public_ip: 52.55.136.115
  annotations:
    github.com/project-slug: veecode-homolog/ec2-application-obs-demo
    grafana/dashboard-selector: ec2-application-obs-demo
    grafana/alert-label-selector: "alertname=ec2-application-obs-demo"
    infracost/project: ec2-application-obs-demo
    backstage.io/techdocs-ref: dir:..
    github.com/workflows: terraform-deploy.yml,start-instance.yml,stop-instance.yml,kubeconfig.yml,terraform-destroy.yml,infracost.yml
    cluster/instructions: "# Run the following commands to import the kubeconfig:\n  ssh -i ./cert.pem -o StrictHostKeyChecking=no $USERNAME@$52.55.136.115 \"mkdir -p .kube && k3d kubeconfig get k3s > ~/.kube/config\"\n  scp -i ./cert.pem $USERNAME@$52.55.136.115:~/.kube/config ~/.kube/config-ec2-application-obs-demo\n  yq -e 'del(.clusters[0].cluster.certificate-authority-data) | .clusters[0].cluster.insecure-skip-tls-verify=true | .clusters[].cluster.server |= sub(\"0.0.0.0\", \"52.55.136.115\")' -i ~/.kube/config-ec2-application-obs-demo\n  export KUBECONFIG=~/.kube/config-ec2-application-obs-demo\n  kubectl get pods -A\n"
spec:
  type: ec2
  lifecycle: experimental
  owner: "group:default/admin"
  environment: 'environment:default/pet-environment-homolog'
